import { ArrowLeft, RotateCcw, Sparkles } from "lucide-react";
import type { CalculateResult } from "../types";

const money = (value: number) => `₹${(value / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;

export function ResultsScreen({ result, onBack, onStartOver }: { result: CalculateResult; onBack: () => void; onStartOver: () => void }) {
  const results = result.people;
  return (
    <section><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm font-bold uppercase tracking-[0.18em] text-coral">Step 4 · Results</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Everyone&apos;s share</h1><p className="mt-2 text-slate-500">A clear breakdown of what each person owes.</p></div><div className="flex items-center gap-2 text-sm font-semibold text-emerald-700"><Sparkles size={17} /> Ready to settle</div></div>
      <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{Object.entries(results).map(([person, personResult]) => <article className="panel overflow-hidden" key={person}><div className="bg-ink p-5 text-white"><p className="text-sm text-slate-300">{person} owes</p><p className="mt-1 text-4xl font-bold">{money(personResult.total)}</p></div><div className="space-y-4 p-5"><div className="space-y-2 text-sm">{Object.entries(personResult.item_shares).map(([item, share]) => <div className="flex justify-between gap-3" key={`${person}-${item}`}><span className="text-slate-600">{item}</span><span className="font-semibold">{money(share)}</span></div>)}</div><div className="border-t border-slate-100 pt-4 text-sm text-slate-500"><div className="flex justify-between"><span>Subtotal</span><span>{money(personResult.subtotal)}</span></div><div className="mt-2 flex justify-between"><span>Discount</span><span className="text-emerald-700">−{money(personResult.discount)}</span></div><div className="mt-2 flex justify-between"><span>Service charge</span><span>{money(personResult.service_charge)}</span></div>      <div className="mt-2 flex justify-between"><span>Tax</span><span>{money(personResult.tax)}</span></div><div className="mt-2 flex justify-between"><span>Adjustment</span><span>{money(personResult.adjustment)}</span></div></div></div></article>)}</div>
      {result.validation.messages.length > 0 && <div className="panel mt-6 bg-amber-50 p-5 text-sm text-amber-900" role="alert"><p className="font-bold">Validation warnings</p><ul className="mt-2 list-disc space-y-1 pl-5">{result.validation.messages.map((message) => <li key={message}>{message}</li>)}</ul></div>}
      <div className="panel mt-6 p-5 sm:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-semibold text-slate-500">Reconciliation</p><h2 className="mt-1 text-xl font-bold">The numbers add up</h2></div><span className={`rounded-full px-3 py-1 text-sm font-bold ${result.difference === 0 ? "bg-mint text-emerald-700" : "bg-amber-100 text-amber-800"}`}>Difference {money(result.difference)}</span></div><div className="grid gap-4 text-sm sm:grid-cols-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-slate-500">Overall bill total</p><p className="mt-1 text-xl font-bold">{money(result.bill_total)}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-slate-500">Allocated total</p><p className="mt-1 text-xl font-bold">{money(result.allocated_total)}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-slate-500">People</p><p className="mt-1 text-xl font-bold">{Object.keys(results).length}</p></div></div></div>
      <div className="mt-6 flex flex-col-reverse justify-between gap-3 sm:flex-row"><button type="button" onClick={onBack} className="button-secondary"><ArrowLeft size={17} /> Back to assignment</button><button type="button" onClick={onStartOver} className="button-primary"><RotateCcw size={17} /> Start over</button></div>
    </section>
  );
}
